### ISSUE TITLE
Salesforce SWE Intern Link Broken

### ISSUE THREAD

**Issue by areeta** [BaruYogesh/Fall2021Internships#6]
<img width="1126" alt="Screen Shot 2020-11-17 at 3 35 21 PM" src="https://user-images.githubusercontent.com/20546538/99463409-82644600-28ea-11eb-8aa8-4d267e23a157.png">

**Comment by BaruYogesh** [comment]
the link worked before, but now it seems to not. I'm assuming salesforce will have an application open at a later time so i'm removing the link.
